- .travis.yml
- karma.js
- package.json
> Travis ECS integration

- karma.js
- package.json
- translations/en.json
- translations/in.json
- translations/pt.json
- yarn.lock
Fixes #21 
- Remove the global lang var
- Stop passing language as a parameter but use the `changeLng` function in i18next
> Allow for language changing

- karma.js
- package.json
- translations/en.json
- translations/in.json
- translations/pt.json
- yarn.lock
Have karma work with the more general borq functions introduced in 0.0.1-alpha.12 and the new FB API.
> Use general borq fns

- karma.js
- package.json
- translations/en.json
- translations/in.json
- translations/pt.json
- yarn.lock
Also have responses in conversations that end with timeouts be sent to Ona.
Fixes #23 
- 
- 
-
> Send timed out conversations to Ona

- karma.js
- package.json
- translations/en.json
- translations/in.json
- translations/pt.json
- yarn.lock
> Keep a record of the network

- translations/in.json
- translations/pt.json
> Add likert explanation for in and pt

- karma.js
Catch failures for the sendGreeting promise
> Catch failed promise for sendGreeting

- karma.js
- package.json
- translations/en.json
- translations/in.json
- translations/pt.json
- yarn.lock
Move users to a "Former Karma" group where they will not be messaged daily.
Fixes #26
> Add an opt out option in the menu

- karma.js
- package.json
- setup.js
- yarn.lock
Successfully make submissions to the API at the end of an interaction.
Fixes #43
> Duplicate submission error from Ona

- karma.js
- translations/en.json
- translations/in.json
- translations/pt.json
Merge the intro into the first question.
Fixes #52
> Freezing after intro text

- translations/en.json
Add space between "10" and "("
Fixes #55
> Grammar fix

- translations/in.json
- translations/pt.json
> Fix quit messages in Portugese and Bahasa translations

- translations/in.json
Add explanation for the 1 to 10 scale in Bahasa
Fixes #57
> Explain bahasa translation 1 to 10 scale

- karma.js
- package.json
- yarn.lock
> Update to botkit 0.0.1 alpha.22

- setup.js
call `services.getUser`
Fixes #71
> Call getUser instead of getRapidPro contact

- karma.js
- translations/en.json
- translations/in.json
- translations/pt.json
Translate share text including and start message.
Fixes #70
> Translate share text

- karma.js
> Replace quitting message for Facebook conversations

- translations/en.json
- translations/in.json
- translations/pt.json
Add an explanation for the 1 to 10 better or worse question in socialConcernChangeScale.
Fixes #82
> Add socialConcernChangeScale explanation

- lib/user.js
- package.json
createUserAndStartConversation sometimes fails because users already exist.
- Use promises for conversations and not nest promises.
> Start the conversation if createUser fails

- index.js
- lib/conversation.js
- package.json
- translations/en.json
- translations/in.json
- translations/pt.json
Listen for text responses to postbacks.
> Listen for message received when waiting for postback responses

- index.js
- package.json
- yarn.lock
Has fixes locales for Indonesian users.
> Depend on borq@v0.0.1-alpha.24

- lib/user.js
Add new exception for RapidPro contacts when starting
new conversations
> Fix `karmaConversation` for freezing conversations

- lib/conversation.js
- translations/en.json
- translations/id.json
- translations/pt.json
Validate responses for `quickReply` questions.
> Validate responses

- index.js
Fetch the rapidpro user and use their language to translate the quit
message. If their language isn't set use the default language.
Fixes #94
> Translate the quit message

- lib/user.js
- When we don't have a user we try to create them
- When we fail at fetching a user we try to create them
- Run this 3 times each and then give up
Fixes #97
> Set a max retries of 3 for create and fetchUser

- index.js
- lib/setup.js
- lib/user.js
We add a "start_date" field for when the user started interacting with the bot.
> Scheduling in rapidpro flow

- .eslintrc.json
- index.js
- lib/conversation.js
- lib/setup.js
- lib/user.js
- package.json
- yarn.lock
Sometimes users send plain punctuation mark messages such as "??", "..." and "...???" we want to listen for these and handle them.
> Listen for punctation messages

- lib/conversations/one.js
- lib/conversations/three.js
- lib/conversations/utils.js
Split by '/' and check that against the first element of each option.
Fixes #104
> Correctly validate relationship questions

- lib/conversations/one.js
- lib/conversations/three.js
- lib/conversations/two.js
- lib/conversations/utils.js
make sure language is set in `conversationEndActions`.
> Lang is not defined on timeout

- lib/conversations/one.js
- lib/conversations/three.js
- lib/conversations/two.js
- lib/conversations/utils.js
- lib/setup.js
- sentry.js
- translations/en.json
- translations/id.json
- translations/pt.json
> Use bot specific goodbye messages

- .eslintrc.json
- Dockerfile
- docker-compose.yml
- index.js
- lib/conversations/one.js
- lib/conversations/three.js
- lib/conversations/two.js
- lib/conversations/utils.js
- lib/setup.js
- lib/user.js
- package.json
- test/lib/conversation.js
- yarn.lock
> Add country to ona submission

- .gitignore
- lib/conversations/one.js
- lib/conversations/three.js
- lib/conversations/two.js
- lib/conversations/utils.js
- lib/setup.js
- lib/user.js
- package.json
- translations/en.json
- translations/id.json
- translations/pt.json
- yarn.lock
Save referrals in the survey as an Ona submission field.
Referrals are from submission to submission, not user to user.
Fixes #109
> Save referrals in survey

- lib/conversations/one.js
- lib/conversations/three.js
- lib/conversations/two.js
- lib/user.js
http.genericCatchRejectedPromise was replaced by logger.logRejectedPromise
Fixes #113
> Remove references to genericCatchRejectedPromise

- .travis.yml
- package.json
- yarn.lock
Set .travis.yml to deploy tags
Fixes #115
> Deploy tags to production

- package.json
- yarn.lock
This makes it possible for us to send messages in order.
> Enable require_delivery messenger event

- lib/conversations/utils.js
- lib/user.js
- package.json
- yarn.lock
Depend on borq 0.0.1-alpha.34 which supports graylog
Add logs for conversation starts and endings
Fixes #118
> Send structured logs to graylog

- lib/conversations/introduction.js
- lib/user.js
- translations/en.json
- translations/id.json
- translations/pt.json
Added an intro conversation in all languages.
However, does not play well with the surveys and general flow.
> Added an introduction conversation
